# Generated by Django 4.2.3 on 2025-05-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=230, null=True)),
                ('location', models.CharField(blank=True, max_length=230, null=True)),
                ('average_salary', models.CharField(blank=True, max_length=230, null=True)),
                ('job_role', models.CharField(blank=True, max_length=230, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
