# Generated by Django 4.2.3 on 2025-05-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placementapp', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='skill_improvement_tips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
