# Generated by Django 5.1.2 on 2025-05-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("placementapp", "0003_history_skill_improvement_tips"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("status", models.CharField(default="unread", max_length=10)),
                ("sent_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
